config/routes.rb
Rails.application.routes.draw do
  resources :beats
  devise_for :users, controllers: {
    registrations: "registrations"
  }
  resources :categories
  get "store/index"
  get "cart", to: "cart#show"
  post "cart/add"
  post "cart/remove"
  get "search", to: "beats#search"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "beats#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/beat.rb
class Beat < ApplicationRecord
  has_many :orderables
  has_many :carts, through: :orderables
  belongs_to :category

  has_one_attached :audio

  has_one_attached :image

  belongs_to :user, optional: true

  validate :title, :bpm, :genre, :scale, :price

  validates :description, length: {maximum: 500, too_long: "%{count} character is the maximum allowed."}

  validates :title, length: {maximum: 100, too_long: "%{count} character is the maximum allowed."}

  validates :price, numericality: {only_integer: true}, length: {maximum: 9}

  validates :category_id, presence: true

  GENRE = %w[HipHop EDM Trap Rap Oldschool Hyperpop Rock Lo-Fi Drill Grime Pluggnb]
  BPM = (50..200).to_a

  def image_as_thumbnail
    image.variant(resize_to_limit: [150, 150]).processed
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :orderables
  has_many :beats, through: :orderables

  def total
    orderables.to_a.sum { |orderable| orderable.total }
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :beats
  validates :name, presence: true, uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :beat
end

app/models/orderable.rb
class Orderable < ApplicationRecord
  belongs_to :beat
  belongs_to :cart

  def total
    beat.price * quantity
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable
  has_many :beats
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  before_action :set_render_cart
  before_action :initialize_cart

  def set_render_cart
    @render_cart = true
  end

  def initialize_cart
    @cart = Cart.find_by(id: session[:cart_id])

    if @cart.nil?
      @cart = Cart.create
      session[:cart_id] = @cart.id

    end
  end
end

app/controllers/beats_controller.rb
class BeatsController < ApplicationController
  before_action :set_beat, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: [:index]
  before_action :set_categories

  # GET /beats or /beats.json
  def index
    @pagy, @beats = pagy(Beat.all.order("created_at desc"), items: 5)
  end

  def search
    @beats = Beat.where("Title LIKE ?", "%" + params[:q] + "%")
  end

  # GET /beats/1 or /beats/1.json
  def show
  end

  # GET /beats/new
  def new
    @beat = current_user.beats.build
  end

  # GET /beats/1/edit
  def edit
  end

  # POST /beats or /beats.json
  def create
    @beat = current_user.beats.build(beat_params)

    respond_to do |format|
      if @beat.save
        format.html { redirect_to beat_url(@beat), notice: "Beat was successfully created." }
        format.json { render :show, status: :created, location: @beat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @beat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beats/1 or /beats/1.json
  def update
    respond_to do |format|
      if @beat.update(beat_params)
        format.html { redirect_to beat_url(@beat), notice: "Beat was successfully updated." }
        format.json { render :show, status: :ok, location: @beat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @beat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beats/1 or /beats/1.json
  def destroy
    @beat.destroy

    respond_to do |format|
      format.html { redirect_to beats_url, notice: "Beat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_beat
    @beat = Beat.find(params[:id])
  end

  private

  # Only allow a list of trusted parameters through.
  def beat_params
    params.require(:beat).permit(:title, :bpm, :genre, :description, :scale, :price, :image, :audio, :category_id)
  end

  def set_categories
    @categories = Category.all.order(:name)
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @render_cart = false
  end

  def add
    @beat = Beat.find_by(id: params[:id])
    quantity = params[:quantity].to_i
    current_orderable = @cart.orderables.find_by(beat_id: @beat.id)
    if current_orderable && quantity > 0
      current_orderable.update(quantity:)
    elsif quantity <= 0
      current_orderable.destroy
    else
      @cart.orderables.create(beat: @beat, quantity: quantity)
    end
  end

  def remove
    Orderable.find_by(id: params[:id]).destroy
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    
	def create
		@beat = Beat.find(params[:beat_id])
	 	@comment = @beat.comments.create(params[:comment].permit(:name, :comment))
		redirect_to beat_path(@beat)	
	end

	def destroy
		@beat = Beat.find(params[:beat_id])
		@comment = @beat.comments.find(params[:id])
		@comment.destroy
		redirect_to beat_path(@beat)
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/beats_helper.rb
module BeatsHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/beats/_beat.html.erb
<div id="<%= dom_id beat %>">
  <p>
    <strong>Title:</strong>
    <%= beat.title %>
  </p>

  <p>
    <strong>Bpm:</strong>
    <%= beat.bpm %>
  </p>

  <p>
    <strong>Genre:</strong>
    <%= beat.genre %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= beat.description %>
  </p>

  <p>
    <strong>Scale:</strong>
    <%= beat.scale %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= beat.category.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= beat.price %>
  </p>
  <%= form_with(url: cart_add_path) do |cart| %>
      <%= cart.hidden_field :id, value: beat.id %>
      <%= cart.number_field :quantity, value: 1, min: 1, max: 1%>
      <%= cart.submit "Add To Cart" %>
  <% end %>
<br />

<strong>Image:</strong>
  <% if beat.image.attached? %>
 
      <%= image_tag beat.image, width:"150px"%>
  <% end %>

  <strong>Track:</strong>
    <% if beat.audio.attached? %>    
          <%= audio_tag(url_for(beat.audio), class:"message-audio", controls: "") %>
          <button><%= link_to "Download Beat", beat.audio, class: "html5" %></button>
      <% end %>
</div>

app/views/beats/_footer.html.erb
<!DOCTYPE html>
<footer>

<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Footer</h5>
    <p class="card-text"> <%= link_to 'Privacy Policy', privacy_path %></p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
 
</footer>

app/views/beats/_form.html.erb
<div class="columns">
  <div class="column is-8 is-centered">


    <%= simple_form_for(@beat) do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>


       <div class="columns">

          <div class="field column is-9">
            <div class="control">
              <%= f.input :title, required: true, input_html: { class: "input"}, wrapper: false, label_html: { class:"label" } %>
            </div>
          </div>

          <div class="field column">
            <div class="control">
              <%= f.input :price, required: true, input_html: { class:"input", maxlength: 7  }, wrapper: false, label_html: { class:"label" } %>
            </div>
          </div>
            
</div>
       

        <div class="field">
          <div class="control">
            <%= f.input :description, required: true, input_html: { class:"textarea" }, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>

        <div class="columns">
          <div class="field column is-4">
            <div class="control">
              <label class="label">BPM</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :bpm, collection: Beat::BPM, prompt: "Select BPM" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-tag"></i>
                </span>
              </div>
            </div>
           </div>

          <div class="field column is-4">
            <div class="control">
              <label class="label">Genre</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :genre, collection: Beat::GENRE, prompt: "Select genre" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-paint-brush"></i>
                </span>
              </div>
            </div>
           </div>

       

           <div class="field">
          <div class="control">
    
            <label class="label">Add Image</label>
              <div class="file">
              <label class="file-label">
                <%= f.file_field :image, direct_upload: true %>  
              </label>
              </div>
            </div>
          </div>

        <div class="field">
          <div class="control">
          <label class="label">Add MP3</label>
              <div class="file">
              <label class="file-label">
                <%= f.file_field :audio, direct_upload: true %>  
              </label>
              </div>
            </div>
          </div>

        <div>
          <%= f.label :category, style: "display: block" %>
          <%= f.select :category_id, options_for_select(@categories.collect { |cat| [cat.name, cat.id]}) %>
        </div>

      

          <div class="field">
          <div class="control">
    
         
      
       </div>

        <hr/>

        <div class="field is-grouped">
          <div class="control">
            <%= f.button :submit, class: 'button is-warning' %>
            <%= link_to 'Cancel', beats_path, class:'button is-light' %>
          </div>
        </div>

      <% end %>
  </div>
</div>

app/views/beats/edit.html.erb
<h1>Editing beat</h1>

<%= render "form", beat: @beat %>

<br>

<div>
  <%= link_to "Show this beat", @beat %> |
  <%= link_to "Back to beats", beats_path %>
</div>

app/views/beats/index.html.erb
<p style="color: green">


<h5>BEAT STORE</h5>

BEATS:
<%= @beats.count %>
 


  
  <tbody>

  <% @beats.each do |beat| %>

    <tr>
    </td>
    </tr>
  
  <% end %>
</tbody>
</table>

<br>


<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">Image</th>
      <th scope="col">Play Audio</th>
      <th scope="col">Title</th>
      <th scope="col">BPM</th>
      <th scope="col">Genre</th>
      <th scope="col">Scale</th>
      <th scope="col">Price ($)</th>
      <th scope="col">Category</th>
      <th scope="col">BUY</th>

    </tr>
  </thead>
  <tbody>
  <% @beats.each do |beat| %>
  
    <tr>
    <td><%=image_tag beat.image, width: "100px" if beat.image.attached? %></td>
    <td><%= audio_tag(url_for(beat.audio), class:"message-audio", controls: "") if beat.audio.attached? %></td>
    <td><%= link_to beat.title + ' ', beat %></td>
    <td><%=beat.bpm%></td>
    <td><%=beat.genre%></td>
    <td><%=beat.scale%></td>
    <td><%=beat.price%></td>
    <td><%=link_to beat.category.name, beat.category%></td>
    <td><%=link_to "Click here to PURCHASE", beat%></td>
   
    
      
      
    </tr>
    <tr>
   <% end %>
    </tr>
  </tbody>

</table>
<%== pagy_nav(@pagy) %>

app/views/beats/new.html.erb
<h1>New beat</h1>

<%= render "form", beat: @beat %>

<br>

<div>
  <%= link_to "Back to beats", beats_path %>
</div>

app/views/beats/search.html.erb
<h1>Search Results:</h1>

<%= render @beats %>

app/views/beats/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @beat %>

<div>
  <%= link_to "Edit this beat", edit_beat_path(@beat) %> |
  <%= link_to "Back to beats", beats_path %>

  <%= button_to "Destroy this beat", @beat, method: :delete %>
</div>

app/views/cart/_cart.html.erb
<%= turbo_frame_tag "tag" do %>
    <h5>CART</h5>
    <% if @cart.orderables.count > 0 %>
        <%= render "cart/orderables" %>
        <p>Total: <%= @cart.total %></p>
            <% else %>
            <p>Your cart is empty</p>
        <% end %>
    <% end %>    

app/views/cart/_orderables.html.erb
<% @cart.orderables.each do |orderable| %>
    <% beat = orderable.beat %>
<div id="<%= "cart-#{beat.id}" %>">
  <p>
    <strong>Title:</strong>
    <%= beat.title %>
  </p>

  <p>
    <strong>Bpm:</strong>
    <%= beat.bpm %>
  </p>

  <p>
    <strong>Genre:</strong>
    <%= beat.genre %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= beat.description %>
  </p>

  <p>
    <strong>Scale:</strong>
    <%= beat.scale %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= beat.price %>
  </p>
        <%= form_with(url: cart_add_path) do |cart| %>
            <%= cart.hidden_field :id, value: beat.id %>
            <%= cart.number_field :quantity, value: orderable.quantity, min: 0, max: 1 %>
            <%= cart.submit "Add To Cart" %>
        <% end %>

        <%= form_with(url: cart_remove_path) do |cart| %>
            <%= cart.hidden_field :id, value: orderable.id %>
            <%= cart.submit "X" %>
        <% end %>
        <strong>Total:</strong>
        <%= orderable.total %>
<br />

<strong>Image:</strong>
  <% if beat.image.attached? %>
 
      <%= image_tag beat.image, width:"150px"%>
  <% end %>

  <strong>Track:</strong>
    <% if beat.audio.attached? %>    
          <%= audio_tag(url_for(beat.audio), class:"message-audio", controls: "") %>
          <button><%= link_to "Download Beat", beat.audio, class: "html5" %></button>
      <% end %>
</div>
<% end %>

app/views/cart/show.html.erb
<h1>Cart#show</h1>
<p>Find me in app/views/cart/show.html.erb</p>

app/views/categories/_categories_picker.html.erb
<h2> Choose your category: </h2>

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Category:</strong>
    <%= category.name %>
    
  </p>

    <% category.beats.each do |beat| %>
      <p>
         <%= audio_tag(url_for(beat.audio), class:"message-audio", controls: "") %>  | <%= link_to "View Beat", beat %>
      </p>
    <% end %>


</div>

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>
<%= render partial: 'categories_picker' %>
<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", category %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/comments/_comment.html.erb
<div class="box">
  <article class="media">
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= comment.name %>:</strong>
          <%= comment.comment %>
        </p>
      </div>
    </div>
     <%= button_to 'Delete', [comment.beat, comment],
                  method: :delete, class: "button is-danger", data: { confirm: 'Are you sure?' } %>
  </article>

</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@beat, @beat.comments.build]) do |f| %>
<!--
collection.build(attributes = {}, …) Returns one or more new objects of the collection type that have been instantiated with attributes and linked to this object through a foreign key, but have not yet been saved. Note: This only works if an associated object already exists, not if it‘s nil!
-->
<div class="field">
  <div class="control">
    <%= f.input :name, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
  </div>
</div>

<div class="field">
  <div class="control">
    <%= f.input :comment, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label' }  %>
  </div>
</div>
<%= f.button :submit, 'Leave a reply', class: "button is-primary" %>
<% end %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Beatstore</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js' %>


    
  </head>

  <body class="<%= yield (:body_class) %>">
    <% if flash[:notice] %>
      <div class="notification is-success global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
    <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>
     <nav class="navbar is-warning" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to root_path, class:"navbar-item" do %>
          <h1 class="title is-5">Beatstore</h1>
        <% end  %>
      <div class="navbar-burger burger" data-target="navbar">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>

      <div id="navbar" class="navbar-menu">
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">

          <% if user_signed_in? %>
            
              <%= link_to 'Upload Beats', new_beat_path, class: "navbar-item button is-dark" %>
           </li>
              <%= link_to 'Your Cart', cart_path, class: "navbar-item button is-dark" %>
              
              <%= link_to 'Categories', categories_path, class: "navbar-item button is-dark" %>
              
               <form class="form-inline my-2 my-lg-0", action="/search">
              <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>

              <div class="navbar-item has-dropdown is-hoverable">
                <%= link_to 'Account', edit_user_registration_path, class: "navbar-link" %>

                <div class="navbar-dropdown is-right">
                  <%= link_to current_user.name, edit_user_registration_path, class:"navbar-item" %>
                  <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"navbar-item" %>
                  
                </div>
              </div>
            <% else %>
            <%= link_to "Sign In", new_user_session_path, class:"navbar-item button is-warning" %>
            <%= link_to "Sign up", new_user_registration_path, class:"navbar-item button is-warning"%>
            <% end %>


           
            </div>
          </div>
        </div>
    </div>
  </nav>

  <%= render partial: "cart/cart" if @render_cart %>

  <div class="container">

    <%= yield %>

  </div>

  </body>
</html>

app/views/store/index.html.erb
<h1>Store#index</h1>
<p>Find me in app/views/store/index.html.erb</p>